server:
  port: 9090
  servlet:
    context-path: /api
    
management: 
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  security:
    user:
      name: admin
      password: secret